### ISSUE TITLE
关于var cAddr atomic.Value的一点疑惑

### ISSUE THREAD

**Issue by hiBlunt** [taoso/utun#2]
您好，我在阅读代码时发现server函数中包含变量var cAddr atomic.Value，如果 Server 通过 c.WriteTo(b, a.(net.Addr)) 发送数据失败，并且在接下来的通信中没有接收到新的有效地址（即 cAddr.Store(nil)），那么 Server 就会停止向客户端发送数据。这样的设计可能会导致上层的失败重传机制失效，请问我的理解对吗？
如果不对的话，可以请您讲一下这个变量的作用吗？感谢！

**Comment by taoso** [comment]
issue 不接受咨询

**Comment by hiBlunt** [comment]
这是可能的bug吧，如果确认这样写没有bug，保持issue为关闭状态即可。
